### ISSUE TITLE
cpf_cnpj dependencie must be manualy included....

### ISSUE THREAD

**Issue by Alan-M-Thomaz** [fnando/validators#11]
Either put "cpf_cnpj" gem as dependencie in the Gemfile, or at least explict that it must be included if someone want to use cpf/cnpj validation...

**Comment by fnando** [comment]
This is covered by the gem:

- https://github.com/fnando/validators/blob/master/lib/validators/validates_cnpj_format_of.rb#L27
- https://github.com/fnando/validators/blob/master/lib/validators/validates_cpf_format_of.rb#L27
