### ISSUE TITLE
Getting 'translation missing' error message

### ISSUE THREAD

**Issue by neidiom** [fnando/validators#13]
First of all this is the perfect gem for my needs, awesome work!

I am getting this error message all the time

````
translation missing: en.activerecord.errors.models.domain.attributes.domain.invalid_hostname
````

**Comment by thiagogabriel** [comment]
You can use the following translation as a base https://github.com/fnando/validators/blob/362cd45c9ec8c904229bf083216b99bffd0475ef/test/support/translations.yml

**Comment by fnando** [comment]
The latest release now bundles translations by default.
