### ISSUE TITLE
#error: cpf_cnpj is not part of the bundle. Add it to Gemfile.

### ISSUE THREAD

**Issue by haroldofurtado** [fnando/validators#14]
Added gem to my GemFile:
gem 'validators'

Runs the command: bundle install

can check it was installed: 
Using validators 3.0.2

In my model I use:

validates_cpf_format_of :cpf

Got the message: cpf_cnpj is not part of the bundle. Add it to Gemfile.

**Comment by fnando** [comment]
This is by design. Not everyone will use this dependency, so if you need it, add it to your own project's Gemfile. ;)
