### ISSUE TITLE
root_domain and email_data gems are not required as dependencies

### ISSUE THREAD

**Issue by bricesanchez** [fnando/validators#18]
Hi @fnando !

Thanks for your work on this gem. 

Since version 3.2.1, 

you require `require "root_domain"`:
https://github.com/fnando/validators/search?q=root_domain

you also `require "email_data"`:
https://github.com/fnando/validators/search?q=email_data

but you only add them as `s.add_development_dependency`

This causes errors in my tests: 
```
LoadError: cannot load such file -- root_domain
```
 or 

```
RuntimeError:
         email_data is not part of the bundle. Add it to Gemfile.
```

Could you add them as `s.add_dependency` ?

**Comment by fnando** [comment]
Hey Brice!

I guess I botched 3.2.1. We already have the concept of optional dependencies in this project; I just forgot to add `root_domain` as such.

#19 fixes that. A new gem version will be released as soon as CI is done running tests.

**Comment by fnando** [comment]
[validators-3.4.1](https://rubygems.org/gems/validators/versions/3.4.1) has been released.

**Comment by bricesanchez** [comment]
Thanks a lot!
