### ISSUE TITLE
Validator raising a constant error for missing dependencies

### ISSUE THREAD

**Issue by mateusluizfb** [fnando/validators#21]
After the gem update, the app began to raise this error:

```
NameError:
       uninitialized constant ActiveModel::Validations::EmailValidator::RootDomain
```

I've consulted the docs and it says:

```
Some validators will require additional dependencies; whenever you get a message like gem-name is not part of the bundle. Add it to your project's Gemfile., all you have to do is adding that gem to your own project's Gemfile.
```

And after digging the code, I've found the required gems and solved the problem.

But the required gems wasn't to be warned before like the docs says?

**Comment by ricardobsilva** [comment]
Hi @mateusluizfb , can you tell me how didi you fix that, please? I have the same issue here in my app.
